kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-server-conf
  labels:
    name: alertmanager-server-conf
  namespace: monitoring
data:
  config.yml: |-
    global:
      smtp_smarthost: "mail:25"
      smtp_from: "alertmanager@example.com"
      smtp_require_tls: false
    templates:
    - "/etc/alertmanager/template/*.tmpl"
    route:
      group_by: ["instance"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: email
      routes:
      - match:
          severity: critical
        receiver: pager
        routes:
          - match:
              service: application
            receiver: support_team
      - match_re:
          severity: ^(warning|critical)$
        receiver: support_team
    receivers:
    - name: "email"
      email_configs:
      - to: "alerts@example.com"
      slack_configs:
      - api_url: https://hooks.slack.com/services/ABC1234
    - name: "support_team"
      email_configs:
      - to: "alerts+support@example.com"
      slack_configs:
      - api_url: https://hooks.slack.com/services/ABC123
        text: "{{ .CommonAnnotations.summary }}"
    - name: 'pager'
      email_configs:
      - to: "alerts+pd@example.com"
      slack_configs:
      - api_url: https://hooks.slack.com/services/ABC123
