version: "3.4"

services:
  app:
    build: .
    image: ${DEMO_APP_IMAGE}
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=development

  redis:
    image: redis
    ports:
      - "6379:6379"
